# Invoked as: cmake -DMIGRATIONS_DIR=... -DOUT_HXX=... -P GenerateEmbeddedMigrations.cmake

if(NOT DEFINED MIGRATIONS_DIR OR NOT DEFINED OUT_HXX)
  message(FATAL_ERROR "GenerateEmbeddedMigrations: MIGRATIONS_DIR and OUT_HXX required")
endif()

file(GLOB _migration_files "${MIGRATIONS_DIR}/[0-9][0-9][0-9][0-9]_*.sql")
list(SORT _migration_files)

set(_entries)
foreach(_file IN LISTS _migration_files)
  get_filename_component(_fname "${_file}" NAME_WE)
  string(REGEX MATCH "^([0-9]+)_(.+)$" _match "${_fname}")
  if(NOT CMAKE_MATCH_1)
    message(FATAL_ERROR "bad migration name '${_fname}' (want NNNN_name.sql)")
  endif()
  math(EXPR _version "${CMAKE_MATCH_1}")
  set(_name "${CMAKE_MATCH_2}")
  file(READ "${_file}" _sql)
  string(APPEND _entries
    "    {${_version}, \"${_name}\", R\"REVLM_SQL(${_sql})REVLM_SQL\"},\n")
endforeach()

set(_content "// Generated by GenerateEmbeddedMigrations.cmake — do not edit.
#pragma once

#include <cstddef>
#include <string_view>

namespace revlm::embedded_migrations
{

struct Migration {
    int version;
    std::string_view name;
    std::string_view sql;
};

inline constexpr Migration kMigrations[] = {
${_entries}};

inline constexpr std::size_t kMigrationCount =
    sizeof(kMigrations) / sizeof(kMigrations[0]);

} // namespace revlm::embedded_migrations
")

get_filename_component(_out_dir "${OUT_HXX}" DIRECTORY)
file(MAKE_DIRECTORY "${_out_dir}")
file(WRITE "${OUT_HXX}.tmp" "${_content}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUT_HXX}.tmp" "${OUT_HXX}")
file(REMOVE "${OUT_HXX}.tmp")
